version: '3.8'
services:
  database:
    image: mysql:latest
    container_name: database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=laravel
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306

  php-apache:
      container_name: php-apache
      build: ./php 
      ports:
          - '8080:80'
      volumes:
        - ./src:/var/www/laravel:consistent
        - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      depends_on:
        - database